import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "SPhone Store",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StoreProvider>
                    <div className=" min-h-screen flex  flex-col justify-between">
                        <Header />
                        <div className=" h-full flex-1 flex justify-center">
                            <div className=" max-w-[1200px] w-[96%] mx-auto">
                                {children}
                            </div>
                        </div>
                        <Footer />
                    </div>
                </StoreProvider>
            </body>
        </html>
    );
}
